/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.musical.ticketing.view;

import java.awt.CardLayout;
import javax.swing.JPanel;
import org.musical.ticketing.view.pages.BrowsePane;
import org.musical.ticketing.view.pages.MusicalDetailsPane;

/**
 *
 * @author suranjanpoudel
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        CardLayout cardLayout = new CardLayout();
        JPanel cardPanel = new JPanel(cardLayout);
        intiCards(cardPanel, cardLayout);
        getContentPane().add(cardPanel);
        
        cardLayout.show(cardPanel, BROWSE_PANEL_ID);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Musical Ticketing System");
        setPreferredSize(new java.awt.Dimension(1150, 1020));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void intiCards(JPanel cardPanel, CardLayout layout) {

        var browsePanel = new BrowsePane();
        browsePanel.setParentCallback(musicalId -> {
            layout.show(cardPanel, MUSICAL_DETAILS_PANEL_ID);
        });

        cardPanel.add(browsePanel, BROWSE_PANEL_ID);
        cardPanel.add(new MusicalDetailsPane(), MUSICAL_DETAILS_PANEL_ID);
    }

    private final String BROWSE_PANEL_ID = "BROWSE_PANEL_ID";
    private final String MUSICAL_DETAILS_PANEL_ID = "MUSICAL_DETAILS_PANEL_ID";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
