/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.musical.ticketing.view;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.musical.ticketing.util.PanelIds;
import org.musical.ticketing.view.messaging.EventListener;
import org.musical.ticketing.view.messaging.ListenerRegistry;
import org.musical.ticketing.view.messaging.events.CustomerCreated;
import org.musical.ticketing.view.messaging.events.MusicalClickedEvent;
import org.musical.ticketing.view.messaging.events.PurchaseEvent;
import org.musical.ticketing.view.messaging.events.StartOverEvent;
import org.musical.ticketing.view.pages.BrowsePane;
import org.musical.ticketing.view.pages.CustomerStartPanel;
import org.musical.ticketing.view.pages.MusicalDetailsPane;
import org.musical.ticketing.view.pages.ReceiptPanel;

/**
 *
 * @author suranjanpoudel
 */
public class MainFrame extends javax.swing.JFrame implements EventListener {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        register();
        initComponents();

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {

        }

        this.layout = new CardLayout();
        this.cardPanel = new JPanel(layout);

        this.musicalDetailsPane = new MusicalDetailsPane();
        this.receiptPanel = new ReceiptPanel();
        this.customerStartPage = new CustomerStartPanel();
        this.browsePanel = new BrowsePane();

        intiCards(cardPanel);

        getContentPane().add(cardPanel);
        layout.show(cardPanel, PanelIds.START_PANEL_ID);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Musical Ticketing System");
        setPreferredSize(new java.awt.Dimension(1150, 1020));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void intiCards(JPanel cardPanel) {
        cardPanel.add(this.browsePanel, PanelIds.BROWSE_PANEL_ID);
        cardPanel.add(this.musicalDetailsPane, PanelIds.MUSICAL_DETAILS_PANEL_ID);
        cardPanel.add(this.receiptPanel, PanelIds.RECEIPT_PANEL_ID);
        cardPanel.add(this.customerStartPage, PanelIds.START_PANEL_ID);

    }

    private void showByPanelId(String panelId) {
        layout.show(cardPanel, panelId);
    }

    private final JPanel cardPanel;
    private final CardLayout layout;
    private final MusicalDetailsPane musicalDetailsPane;
    private final ReceiptPanel receiptPanel;
    private final CustomerStartPanel customerStartPage;
    private final BrowsePane browsePanel;

    @Override
    public void handleEvent(Object event) {
        if (event instanceof CustomerCreated customerCreated) {
            showByPanelId(PanelIds.BROWSE_PANEL_ID);
            browsePanel.setCustomerId(customerCreated.customerId());
            browsePanel.render();
        } else if (event instanceof MusicalClickedEvent musicalClickedEvent) {
            showByPanelId(PanelIds.MUSICAL_DETAILS_PANEL_ID);
            musicalDetailsPane.render(musicalClickedEvent.musicalId(), musicalClickedEvent.customerId());
        } else if (event instanceof PurchaseEvent purchaseEvent) {
            showByPanelId(PanelIds.RECEIPT_PANEL_ID);
            receiptPanel.render(purchaseEvent);
        } else if (event instanceof StartOverEvent) {
            showByPanelId(PanelIds.START_PANEL_ID);
        }
    }

    @Override
    public void register() {
        ListenerRegistry.register(CustomerCreated.class, this);
        ListenerRegistry.register(MusicalClickedEvent.class, this);
        ListenerRegistry.register(PurchaseEvent.class, this);
        ListenerRegistry.register(StartOverEvent.class, this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
