package org.musical.ticketing.view.pages;

import java.util.function.Consumer;
import javax.swing.JScrollPane;
import org.musical.ticketing.view.components.BrowseMusicalsPane;
import org.musical.ticketing.view.components.SearchComponent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author suranjanpoudel
 */
public class BrowsePane extends javax.swing.JPanel {

    /**
     * Creates new form BrowsePane
     */
    public BrowsePane() {
        initComponents();
        browseSplitPane.setTopComponent(new SearchComponent());

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseSplitPane = new javax.swing.JSplitPane();

        browseSplitPane.setDividerLocation(80);
        browseSplitPane.setDividerSize(2);
        browseSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(browseSplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(browseSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setParentCallback(Consumer<Long> callback) {
        var browseMusicalPane = new BrowseMusicalsPane();
        browseMusicalPane.setParentCallback(callback);
        browseSplitPane.setBottomComponent(new JScrollPane(browseMusicalPane));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane browseSplitPane;
    // End of variables declaration//GEN-END:variables
}
