package org.musical.ticketing.view.pages;

import javax.swing.JScrollPane;
import org.musical.ticketing.view.components.BrowseMusicalsPane;
import org.musical.ticketing.view.components.SearchComponent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author suranjanpoudel
 */
public class BrowsePane extends javax.swing.JPanel {

    /**
     * Creates new form BrowsePane
     */
    public BrowsePane() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseSplitPane = new javax.swing.JSplitPane();

        browseSplitPane.setDividerLocation(80);
        browseSplitPane.setDividerSize(2);
        browseSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(browseSplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(browseSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void render() {
        var browseMusicalsPane = new BrowseMusicalsPane(customerId);

        var scrollPane = new JScrollPane(browseMusicalsPane);
        browseSplitPane.setBottomComponent(scrollPane);

        var searchComponent =  new SearchComponent();

        browseSplitPane.setTopComponent(searchComponent);

        browseMusicalsPane.showMusicals();
    }

    private Long customerId;

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane browseSplitPane;
    // End of variables declaration//GEN-END:variables
}
