/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.musical.ticketing.view.pages;

import org.musical.ticketing.view.components.BriefMusicalComponent;

/**
 *
 * @author suranjanpoudel
 */
public class MusicalDetailsPane extends javax.swing.JPanel {

    /**
     * Creates new form MusicalDetailsPane
     */
    public MusicalDetailsPane() {
        initComponents();

        splittedPanel.setLeftComponent(new BriefMusicalComponent(1l, false));

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splittedPanel = new javax.swing.JSplitPane();

        setLayout(new java.awt.CardLayout());

        splittedPanel.setBackground(new java.awt.Color(255, 204, 204));
        splittedPanel.setDividerLocation(400);
        splittedPanel.setDividerSize(1);
        add(splittedPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane splittedPanel;
    // End of variables declaration//GEN-END:variables
}
