/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.musical.ticketing.view.pages;

import org.musical.ticketing.util.MainFrameContext;
import org.musical.ticketing.util.PanelIds;
import org.musical.ticketing.view.components.BriefMusicalComponent;
import org.musical.ticketing.view.components.calendar.CalendarView;

/**
 *
 * @author suranjanpoudel
 */
public class MusicalDetailsPane extends javax.swing.JPanel {

    /**
     * Creates new form MusicalDetailsPane
     */
    public MusicalDetailsPane() {
        initComponents();

        musicalDescriptionSplitPanel.setBottomComponent(new BriefMusicalComponent(1l, false));
        splittedPanel.setRightComponent(new CalendarView());

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splittedPanel = new javax.swing.JSplitPane();
        musicalDescriptionSplitPanel = new javax.swing.JSplitPane();
        backToSearchButton = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        splittedPanel.setBackground(new java.awt.Color(255, 204, 204));
        splittedPanel.setDividerLocation(400);
        splittedPanel.setDividerSize(1);

        musicalDescriptionSplitPanel.setDividerLocation(35);
        musicalDescriptionSplitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        backToSearchButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        backToSearchButton.setText("<- Go Back to Search");
        backToSearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToSearchButtonMouseClicked(evt);
            }
        });
        backToSearchButton.addActionListener(this::backToSearchButtonActionPerformed);
        musicalDescriptionSplitPanel.setTopComponent(backToSearchButton);

        splittedPanel.setLeftComponent(musicalDescriptionSplitPanel);

        add(splittedPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void backToSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToSearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backToSearchButtonActionPerformed

    private void backToSearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToSearchButtonMouseClicked
        var rootFrame = MainFrameContext.instance().getRootFrame();
        rootFrame.showByPanelId(PanelIds.BROWSE_PANEL_ID);
    }//GEN-LAST:event_backToSearchButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToSearchButton;
    private javax.swing.JSplitPane musicalDescriptionSplitPanel;
    private javax.swing.JSplitPane splittedPanel;
    // End of variables declaration//GEN-END:variables
}
