/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.musical.ticketing.view.pages;

import org.musical.ticketing.view.components.TicketDetailsData;
import org.musical.ticketing.view.messaging.ListenerRegistry;
import org.musical.ticketing.view.messaging.events.MusicalClickedEvent;

/**
 *
 * @author suranjanpoudel
 */
public class ReceiptPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReceiptPage
     */
    public ReceiptPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        backButtonPanel = new javax.swing.JPanel();
        backToMusicalDescriptionButton = new javax.swing.JButton();
        receiptTitleLabel = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        receiptScroller = new javax.swing.JScrollPane();
        receiptTextView = new javax.swing.JTextArea();

        setLayout(new java.awt.GridBagLayout());

        backButtonPanel.setLayout(new java.awt.GridLayout(0, 3));

        backToMusicalDescriptionButton.setText("<-- Back to Musical Details");
        backToMusicalDescriptionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMusicalDescriptionButtonMouseClicked(evt);
            }
        });
        backToMusicalDescriptionButton.addActionListener(this::backToMusicalDescriptionButtonActionPerformed);
        backButtonPanel.add(backToMusicalDescriptionButton);

        receiptTitleLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        receiptTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receiptTitleLabel.setText("Receipt");
        backButtonPanel.add(receiptTitleLabel);

        printButton.setText("Print");
        printButton.addActionListener(this::printButtonActionPerformed);
        backButtonPanel.add(printButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.05;
        add(backButtonPanel, gridBagConstraints);

        receiptTextView.setColumns(20);
        receiptTextView.setRows(5);
        receiptScroller.setViewportView(receiptTextView);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.95;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(receiptScroller, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printButtonActionPerformed

    private void backToMusicalDescriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMusicalDescriptionButtonActionPerformed
        evt.getActionCommand();
    }//GEN-LAST:event_backToMusicalDescriptionButtonActionPerformed

    private void backToMusicalDescriptionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMusicalDescriptionButtonMouseClicked
        ListenerRegistry.notify(new MusicalClickedEvent(data.musicalId(), data.customerId()));
    }//GEN-LAST:event_backToMusicalDescriptionButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backButtonPanel;
    private javax.swing.JButton backToMusicalDescriptionButton;
    private javax.swing.JButton printButton;
    private javax.swing.JScrollPane receiptScroller;
    private javax.swing.JTextArea receiptTextView;
    private javax.swing.JLabel receiptTitleLabel;
    // End of variables declaration//GEN-END:variables

    private TicketDetailsData data;

    public void render(TicketDetailsData data) {
        this.data = data;
    }
}
