package org.musical.ticketing.view.components;

import java.awt.Color;
import java.util.function.Consumer;
import javax.swing.ImageIcon;
import org.musical.ticketing.util.ImageUtils;

/**
 *
 * @author suranjanpoudel
 */
public class BriefMusicalComponent extends javax.swing.JPanel {

    private final Long musicalId;
    private final boolean isBrowsing;

    /**
     * Creates new form BriefMusicalComponent
     */
    public BriefMusicalComponent(Long musicalId, boolean isBrowsing) {
        this.musicalId = musicalId;
        this.isBrowsing = isBrowsing;
        initComponents();

        var image = ImageUtils.getImage("test_image.jpeg");
        if (image != null) {
            imageLabel.setIcon(new ImageIcon(image));
        }

        if (isBrowsing) {
            musicalDescriptionText.setEditable(false);
            musicalDescriptionText.setEnabled(false);
            musicalDescriptionText.setVisible(false);
            musicalDescriptionScrollPane.setVisible(false);
        }

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        musicalTitleLabel = new javax.swing.JLabel();
        musicalDurationLabel = new javax.swing.JLabel();
        theatreNameLabel = new javax.swing.JLabel();
        musicalDescriptionScrollPane = new javax.swing.JScrollPane();
        musicalDescriptionText = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(280, 530));
        setMinimumSize(new java.awt.Dimension(280, 530));
        setMixingCutoutShape(null);
        setPreferredSize(new java.awt.Dimension(280, 530));
        setSize(new java.awt.Dimension(280, 500));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        musicalTitleLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        musicalTitleLabel.setText("Musical Title");

        musicalDurationLabel.setText("Duration: ");

        theatreNameLabel.setText("Show At: ");

        musicalDescriptionText.setColumns(20);
        musicalDescriptionText.setRows(5);
        musicalDescriptionScrollPane.setViewportView(musicalDescriptionText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(theatreNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(musicalDurationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(musicalTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(musicalDescriptionScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(musicalTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(theatreNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(musicalDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(musicalDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (isBrowsing && callback != null) {
            callback.accept(this.musicalId);
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JScrollPane musicalDescriptionScrollPane;
    private javax.swing.JTextArea musicalDescriptionText;
    private javax.swing.JLabel musicalDurationLabel;
    private javax.swing.JLabel musicalTitleLabel;
    private javax.swing.JLabel theatreNameLabel;
    // End of variables declaration//GEN-END:variables

    public Long getMusicalId() {
        return musicalId;
    }

    private Consumer<Long> callback;

    public void setParentCallback(Consumer<Long> callback) {
        this.callback = callback;
    }

}
