package org.musical.ticketing.view.components;

import java.awt.Color;
import javax.swing.ImageIcon;
import org.musical.ticketing.domain.Musical;
import org.musical.ticketing.util.ImageUtils;
import org.musical.ticketing.view.messaging.ListenerRegistry;
import org.musical.ticketing.view.messaging.events.MusicalClickedEvent;

/**
 *
 * @author suranjanpoudel
 */
public class BriefMusicalComponent extends javax.swing.JPanel {

    private final Long musicalId;
    private final Long customerId;
    private final boolean isBrowsing;

    /**
     * Creates new form BriefMusicalComponentØ
     *
     * @param musical
     * @param customerId
     * @param isBrowsing
     */
    public BriefMusicalComponent(Musical musical, Long customerId, boolean isBrowsing) {
        this.musicalId = musical.id();
        this.customerId = customerId;
        this.isBrowsing = isBrowsing;
        initComponents();

        var image = ImageUtils.getImage(musical.thumbnailImageUrl());
        if (image != null) {
            imageLabel.setIcon(new ImageIcon(image));
        }

        musicalTitleLabel.setText(musical.title());
        musicalDurationLabel.setText(musical.durationToString());
        theatreNameLabel.setText(musical.theaterName());

        if (isBrowsing) {
            descriptionTextPane.setEditable(false);
            descriptionTextPane.setEnabled(false);
            descriptionTextPane.setVisible(false);
            musicalDescriptionScrollPane.setVisible(false);
        } else {
            descriptionTextPane.setEditable(false);
            descriptionTextPane.setText(musical.description());
        }

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        imageLabel = new javax.swing.JLabel();
        musicalTitleLabel = new javax.swing.JLabel();
        theatreNameLabel = new javax.swing.JLabel();
        musicalDurationLabel = new javax.swing.JLabel();
        musicalDescriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextPane = new javax.swing.JEditorPane();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(3000, 3000));
        setMinimumSize(new java.awt.Dimension(280, 530));
        setMixingCutoutShape(null);
        setPreferredSize(new java.awt.Dimension(280, 530));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(imageLabel, gridBagConstraints);

        musicalTitleLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        musicalTitleLabel.setText("Musical Title");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        add(musicalTitleLabel, gridBagConstraints);

        theatreNameLabel.setText("Show At: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        add(theatreNameLabel, gridBagConstraints);

        musicalDurationLabel.setText("Duration: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        add(musicalDurationLabel, gridBagConstraints);

        musicalDescriptionScrollPane.setBorder(null);
        musicalDescriptionScrollPane.setViewportView(null);

        descriptionTextPane.setContentType("text/html");
        descriptionTextPane.setMinimumSize(new java.awt.Dimension(400, 300));
        descriptionTextPane.setPreferredSize(new java.awt.Dimension(400, 300));
        musicalDescriptionScrollPane.setViewportView(descriptionTextPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(musicalDescriptionScrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (isBrowsing) {
            ListenerRegistry.notify(new MusicalClickedEvent(musicalId, customerId));
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane descriptionTextPane;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JScrollPane musicalDescriptionScrollPane;
    private javax.swing.JLabel musicalDurationLabel;
    private javax.swing.JLabel musicalTitleLabel;
    private javax.swing.JLabel theatreNameLabel;
    // End of variables declaration//GEN-END:variables

}
