/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.musical.ticketing.view.components;

import java.util.function.Consumer;

/**
 *
 * @author suranjanpoudel
 */
public class BrowseMusicalsPane extends javax.swing.JPanel {

    /**
     * Creates new form BrowseMusicalsPane
     */
    public BrowseMusicalsPane() {
        initComponents();

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setLocation(new java.awt.Point(20, 20));
        setLayout(new java.awt.GridLayout(0, 3, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    public void setParentCallback(Consumer<Long> callback) {
        showMusicals(callback);
    }

    public void showMusicals(Consumer<Long> callback) {
        for (long i = 0; i < 20; i++) {
            var musicalComponent = new BriefMusicalComponent(i, true);
            musicalComponent.setParentCallback(callback);
            add(musicalComponent);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
