/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.musical.ticketing.view.components.calendar;

/**
 *
 * @author suranjanpoudel
 */
public class CalendarCell extends javax.swing.JPanel {

    private final CellData cellData;

    /**
     * Creates new form CalendarCell
     *
     * @param cellData
     */
    public CalendarCell(CellData cellData) {
        this.cellData = cellData;

        initComponents();

        dayOfMonthLabel.setText(cellData.title());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dayOfMonthLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setLayout(new java.awt.GridBagLayout());

        dayOfMonthLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        dayOfMonthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayOfMonthLabel.setText("5");
        add(dayOfMonthLabel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayOfMonthLabel;
    // End of variables declaration//GEN-END:variables
}
