/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.musical.ticketing.view.components.calendar;

/**
 *
 * @author suranjanpoudel
 */
public class CalendarView extends javax.swing.JPanel {

    /**
     * Creates new form CalendarView
     */
    public CalendarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        calendarControlsPanel1 = new org.musical.ticketing.view.components.calendar.CalendarControlsPanel();
        calendarPane = new org.musical.ticketing.view.components.calendar.CalendarPanel();
        timeSlotScroll = new javax.swing.JScrollPane();
        ticketTimeSlotPlane = new org.musical.ticketing.view.components.calendar.TicketTimeSlotPlane();
        ticketTypeChooser = new org.musical.ticketing.view.components.calendar.TicketTypeChooser();
        totalCostPane = new org.musical.ticketing.view.components.calendar.TotalCostPane();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.01;
        add(calendarControlsPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.6;
        add(calendarPane, gridBagConstraints);

        timeSlotScroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        timeSlotScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        ticketTimeSlotPlane.setMaximumSize(new java.awt.Dimension(70, 90));
        ticketTimeSlotPlane.setMinimumSize(new java.awt.Dimension(70, 90));
        ticketTimeSlotPlane.setPreferredSize(new java.awt.Dimension(70, 90));
        timeSlotScroll.setViewportView(ticketTimeSlotPlane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 15);
        add(timeSlotScroll, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 10, 15);
        add(ticketTypeChooser, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(totalCostPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.musical.ticketing.view.components.calendar.CalendarControlsPanel calendarControlsPanel1;
    private org.musical.ticketing.view.components.calendar.CalendarPanel calendarPane;
    private org.musical.ticketing.view.components.calendar.TicketTimeSlotPlane ticketTimeSlotPlane;
    private org.musical.ticketing.view.components.calendar.TicketTypeChooser ticketTypeChooser;
    private javax.swing.JScrollPane timeSlotScroll;
    private org.musical.ticketing.view.components.calendar.TotalCostPane totalCostPane;
    // End of variables declaration//GEN-END:variables
}
