/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.musical.ticketing.view.components.calendar;

import java.time.YearMonth;
import java.time.format.TextStyle;
import java.util.Locale;
import org.musical.ticketing.view.messaging.ListenerRegistry;
import org.musical.ticketing.view.messaging.events.CurrentYearMonthChanged;

/**
 *
 * @author suranjanpoudel
 */
public class CalendarControlsPanel extends javax.swing.JPanel {

    /**
     * Creates new form CalendarControllsPanel
     */
    public CalendarControlsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previousYearButton = new javax.swing.JButton();
        previousMonthButton = new javax.swing.JButton();
        yearMonthLabel = new javax.swing.JLabel();
        nextMonthButton = new javax.swing.JButton();
        nextYearButton = new javax.swing.JButton();

        previousYearButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        previousYearButton.setText("<<");
        previousYearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        previousYearButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previousYearButton.setIconTextGap(10);
        previousYearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousYearButtonMouseClicked(evt);
            }
        });
        add(previousYearButton);

        previousMonthButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        previousMonthButton.setText("<");
        previousMonthButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        previousMonthButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previousMonthButton.setIconTextGap(10);
        previousMonthButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousMonthButtonMouseClicked(evt);
            }
        });
        add(previousMonthButton);

        yearMonthLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        yearMonthLabel.setText("January, 2023");
        yearMonthLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        yearMonthLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        yearMonthLabel.setIconTextGap(10);
        add(yearMonthLabel);

        nextMonthButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        nextMonthButton.setText(">");
        nextMonthButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextMonthButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextMonthButton.setIconTextGap(10);
        nextMonthButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMonthButtonMouseClicked(evt);
            }
        });
        add(nextMonthButton);

        nextYearButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        nextYearButton.setText(">>");
        nextYearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextYearButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextYearButton.setIconTextGap(10);
        nextYearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextYearButtonMouseClicked(evt);
            }
        });
        add(nextYearButton);
    }// </editor-fold>//GEN-END:initComponents

    private void previousYearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousYearButtonMouseClicked
        initControls(this.currentYearMonth.minusYears(1));
        ListenerRegistry.notify(new CurrentYearMonthChanged(currentYearMonth));
    }//GEN-LAST:event_previousYearButtonMouseClicked

    private void previousMonthButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousMonthButtonMouseClicked
        initControls(this.currentYearMonth.minusMonths(1));
        ListenerRegistry.notify(new CurrentYearMonthChanged(currentYearMonth));
    }//GEN-LAST:event_previousMonthButtonMouseClicked

    private void nextMonthButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMonthButtonMouseClicked
        initControls(this.currentYearMonth.plusMonths(1));
        ListenerRegistry.notify(new CurrentYearMonthChanged(currentYearMonth));
    }//GEN-LAST:event_nextMonthButtonMouseClicked

    private void nextYearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextYearButtonMouseClicked
        initControls(this.currentYearMonth.plusYears(1));
        ListenerRegistry.notify(new CurrentYearMonthChanged(currentYearMonth));
    }//GEN-LAST:event_nextYearButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton nextMonthButton;
    private javax.swing.JButton nextYearButton;
    private javax.swing.JButton previousMonthButton;
    private javax.swing.JButton previousYearButton;
    private javax.swing.JLabel yearMonthLabel;
    // End of variables declaration//GEN-END:variables

    private YearMonth currentYearMonth;

    public void initControls(YearMonth now) {
        this.currentYearMonth = now;
        yearMonthLabel.setText(now.getMonth().getDisplayName(TextStyle.FULL, Locale.UK) + ", " + now.getYear());
    }
}
