/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.musical.ticketing.view.components.calendar;

/**
 *
 * @author suranjanpoudel
 */
public class CalendarView extends javax.swing.JPanel {

    private final Long musicalId;
    
    /**
     * Creates new form CalendarView
     * @param musicalId
     */
    public CalendarView(Long musicalId) {
        initComponents();
        this.musicalId = musicalId;
        accountingPane.setMusicalId(musicalId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        calendarControlsPanel = new org.musical.ticketing.view.components.calendar.CalendarControlsPanel();
        calendarPane = new org.musical.ticketing.view.components.calendar.CalendarPanel();
        ticketTimeSlotPlane = new org.musical.ticketing.view.components.calendar.TicketTimeSlotPlane();
        accountingPane = new org.musical.ticketing.view.components.calendar.AccountingPane();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.01;
        add(calendarControlsPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        add(calendarPane, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        add(ticketTimeSlotPlane, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.35;
        add(accountingPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.musical.ticketing.view.components.calendar.AccountingPane accountingPane;
    private org.musical.ticketing.view.components.calendar.CalendarControlsPanel calendarControlsPanel;
    private org.musical.ticketing.view.components.calendar.CalendarPanel calendarPane;
    private org.musical.ticketing.view.components.calendar.TicketTimeSlotPlane ticketTimeSlotPlane;
    // End of variables declaration//GEN-END:variables
}
