/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.musical.ticketing.view.components.calendar;

/**
 *
 * @author suranjanpoudel
 */
public class CalendarControlsPanel extends javax.swing.JPanel {

    /**
     * Creates new form CalendarControllsPanel
     */
    public CalendarControlsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previousYearButton = new javax.swing.JButton();
        previousMonthButton = new javax.swing.JButton();
        yearMonthLabel = new javax.swing.JLabel();
        nextMonthButton = new javax.swing.JButton();
        nextYearButton = new javax.swing.JButton();

        previousYearButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        previousYearButton.setText("<<");
        previousYearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        previousYearButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previousYearButton.setIconTextGap(10);
        add(previousYearButton);

        previousMonthButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        previousMonthButton.setText("<");
        previousMonthButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        previousMonthButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previousMonthButton.setIconTextGap(10);
        add(previousMonthButton);

        yearMonthLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        yearMonthLabel.setText("January, 2023");
        yearMonthLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        yearMonthLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        yearMonthLabel.setIconTextGap(10);
        add(yearMonthLabel);

        nextMonthButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        nextMonthButton.setText(">");
        nextMonthButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextMonthButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextMonthButton.setIconTextGap(10);
        add(nextMonthButton);

        nextYearButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        nextYearButton.setText(">>");
        nextYearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextYearButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextYearButton.setIconTextGap(10);
        add(nextYearButton);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton nextMonthButton;
    private javax.swing.JButton nextYearButton;
    private javax.swing.JButton previousMonthButton;
    private javax.swing.JButton previousYearButton;
    private javax.swing.JLabel yearMonthLabel;
    // End of variables declaration//GEN-END:variables
}
