/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.musical.ticketing.view.components.calendar;

/**
 *
 * @author suranjanpoudel
 */
public class TicketTypeChooser extends javax.swing.JPanel {

    /**
     * Creates new form TicketTypeChooser
     */
    public TicketTypeChooser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ticketTypeLable = new javax.swing.JLabel();
        ticketTypeComboBox = new javax.swing.JComboBox<>();

        setLayout(new java.awt.GridBagLayout());

        ticketTypeLable.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        ticketTypeLable.setText("Select Ticket Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(ticketTypeLable, gridBagConstraints);

        ticketTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ticketTypeComboBox.setMinimumSize(new java.awt.Dimension(72, 50));
        ticketTypeComboBox.setPreferredSize(new java.awt.Dimension(72, 50));
        ticketTypeComboBox.addActionListener(this::ticketTypeComboBoxActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.9;
        add(ticketTypeComboBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void ticketTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketTypeComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ticketTypeComboBox;
    private javax.swing.JLabel ticketTypeLable;
    // End of variables declaration//GEN-END:variables
}
