/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.musical.ticketing.view.components.calendar;

import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JToggleButton;

/**
 *
 * @author suranjanpoudel
 */
public class TicketTimeSlotPlane extends javax.swing.JPanel {

    /**
     * Creates new form TicketTimeSlotPlane
     */
    public TicketTimeSlotPlane() {
        initComponents();
        
        List<TimeSlotData> timeSlots = new ArrayList<>();
        timeSlots.add(new TimeSlotData(0, LocalTime.now(), LocalTime.now().plusHours(1), 5));
        timeSlots.add(new TimeSlotData(1, LocalTime.now().plusHours(2), LocalTime.now().plusHours(3), 6));
        timeSlots.add(new TimeSlotData(2, LocalTime.now().plusHours(4), LocalTime.now().plusHours(5), 5));
        timeSlots.add(new TimeSlotData(3, LocalTime.now().plusHours(6), LocalTime.now().plusHours(7), 5));
        timeSlots.add(new TimeSlotData(4, LocalTime.now().plusHours(8), LocalTime.now().plusHours(9), 6));
        timeSlots.add(new TimeSlotData(5, LocalTime.now().plusHours(10), LocalTime.now().plusHours(11), 5));
        renderTimeSlots(timeSlots);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(100, 70));
        setMinimumSize(new java.awt.Dimension(100, 70));
        setPreferredSize(new java.awt.Dimension(100, 70));
        setLayout(new java.awt.GridLayout(0, 3, 1, 1));
    }// </editor-fold>//GEN-END:initComponents

    public void renderTimeSlots(List<TimeSlotData> timeSlots) {
        int i=0;
        for(var slot : timeSlots) {
            var timeSlotToggle = new JToggleButton();
            timeSlotToggle.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); 
            timeSlotToggle.setText(slot.formattedText());
            add(timeSlotToggle, i++);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
